name: Sync and Encrypt Registration Data

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install google-api-python-client google-auth

      - name: Run encrypt script
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: python encrypt_and_push.py

      - name: Commit encrypted file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add encrypted_data.json.gpg
          git commit -m "Auto-update encrypted data" || echo "No changes"
          git push
